{
 "title": "Silk dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Vulnerabilities found", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Qualys vulnerabilities detected, per host",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $match: {\n      \"QualysScan.scan_data.vuln.list\": { $exists: true }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: 1,\n      vulnListLength: { $size: \"$QualysScan.scan_data.vuln.list\" }\n    }\n  },\n  {\n    $sort: {\n      vulnListLength: 1 // Use -1 for descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Tenable critical, per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $match: {\n      \"TenableScan.scan_data.vuln_counts.critical\": { $exists: true }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: 1,\n      \"Critical\": \"$TenableScan.scan_data.vuln_counts.critical\"\n    }\n  },\n  {\n    $sort: {\n      \"Critical\": 1 // Use -1 for descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Tenable high, per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $match: {\n      \"TenableScan.scan_data.vuln_counts.high\": { $exists: true }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: 1,\n      \"Critical\": \"$TenableScan.scan_data.vuln_counts.high\"\n    }\n  },\n  {\n    $sort: {\n      \"Critical\": 1 // Use -1 for descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Crowdstrike management",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $project: {\n      hostname: 1,\n      \"Provisioned?\": {\n        $cond: {\n          if: { $eq: [\"$CrowdstrikeScan.scan_data.provision_status\", \"Provisioned\"] },\n          then: true,\n          else: false\n        }\n      },\n      _id: 0\n    }\n  },\n  {\n    $sort: {\n      \"Provisioned?\": 1 // Sort by Provisioned? in descending order (true first, false last)\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Tenable medium, per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $match: {\n      \"TenableScan.scan_data.vuln_counts.medium\": { $exists: true }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: 1,\n      \"Critical\": \"$TenableScan.scan_data.vuln_counts.medium\"\n    }\n  },\n  {\n    $sort: {\n      \"Critical\": 1 // Use -1 for descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Tenable low, per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $match: {\n      \"TenableScan.scan_data.vuln_counts.low\": { $exists: true }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: 1,\n      \"Critical\": \"$TenableScan.scan_data.vuln_counts.low\"\n    }\n  },\n  {\n    $sort: {\n      \"Critical\": 1 // Use -1 for descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  { "title": "Host scan status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Full coverage status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $project: {\n      hostname: 1,\n      allScansPresent: {\n        $cond: {\n          if: {\n            $and: [\n              { $gt: [\"$CrowdstrikeScan\", null] },\n              { $gt: [\"$QualysScan\", null] },\n              { $gt: [\"$TenableScan\", null] }\n            ]\n          },\n          then: true,\n          else: false\n        }\n      }\n    }\n  },\n  {\n    $group: {\n      _id: null,\n      total: { $sum: 1 },\n      trueCount: {\n        $sum: {\n          $cond: { if: \"$allScansPresent\", then: 1, else: 0 }\n        }\n      }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      percentage: {\n        $multiply: [{ $divide: [\"$trueCount\", \"$total\"] }, 100]\n      }\n    }\n  }\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "Full coverage by 3 providers",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 7, "y": 20 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $project: {\n      hostname: 1,  // Include the hostname field\n      allScansPresent: {\n        $cond: {\n          if: {\n            $and: [\n              { $gt: [\"$CrowdstrikeScan\", null] },\n              { $gt: [\"$QualysScan\", null] },\n              { $gt: [\"$TenableScan\", null] }\n            ]\n          },\n          then: true,\n          else: false\n        }\n      }\n    }\n  },\n  {\n    $group: {\n      _id: \"$hostname\",\n      \"3 scans?\": { $first: \"$allScansPresent\" }\n    }\n  },\n  {\n    $project: {\n      _id: 0,\n      hostname: \"$_id\",\n      \"3 scans?\": 1\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Last check-in (from any agent)",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $project: {\n      hostname: 1,\n      mostRecentDate: {\n        $max: [\n          '$QualysScan.scan_data.lastComplianceScan',\n          '$CrowdstrikeScan.scan_data.last_seen',\n          '$TenableScan.scan_data.last_observed.date'\n        ]\n      }\n    }\n  },\n  {\n    $group: {\n      _id: \"$hostname\",\n      mostRecentDate: { $max: \"$mostRecentDate\" }\n    }\n  },\n  {\n    $addFields: {\n      \">30 days ago?\": {\n        $cond: [\n          {\n            $lt: [\n              \"$mostRecentDate\",\n              { $subtract: [new Date(), 1000 * 60 * 60 * 24 * 30] }\n            ]\n          },\n          true,\n          false\n        ]\n      }\n    }\n  },\n  {\n    $project: {\n      hostname: '$_id',\n      \"Last seen\": \"$mostRecentDate\",\n      \">30 days ago?\": 1,\n      _id: 0\n    }\n  },\n  {\n    $sort: {\n      \"Last seen\": -1\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Scans from each data source",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $project: {\n      field1: {\n        $cond: {\n          if: {\n            $gt: [\"$CrowdstrikeScan\", null]\n          },\n          then: 1,\n          else: 0\n        }\n      },\n      field2: {\n        $cond: {\n          if: {\n            $gt: [\"$QualysScan\", null]\n          },\n          then: 1,\n          else: 0\n        }\n      },\n      field3: {\n        $cond: {\n          if: {\n            $gt: [\"$TenableScan\", null]\n          },\n          then: 1,\n          else: 0\n        }\n      }\n    }\n  },\n  {\n    $group: {\n      _id: null,\n      \"Crowdstrike\": {\n        $sum: \"$field1\"\n      },\n      \"Qualys\": {\n        $sum: \"$field2\"\n      },\n      \"Tenable\": {\n        $sum: \"$field3\"\n      }\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  { "title": "Operating Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.normalized.aggregate(\n  [\n    {\n      $group: {\n        _id: {\n          $ifNull: [\n            '$QualysScan.scan_data.os',\n            '$CrowdstrikeScan.scan_data.os_version',\n            '$TenableScan.scan_data.operating_systems'\n          ]\n        },\n        count: { $sum: 1 },\n        results: {\n          $push: { hostname: '$hostname' }\n        }\n      }\n    },\n    {\n      $project: {\n        'Operating System': '$_id',\n        count: 1,\n        results: 1,\n        _id: 0\n      }\n    }\n  ]\n)",
     "type": "table"
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 33 },
   "targets": [
    {
     "target": "db.normalized.aggregate([\n  {\n    $group: {\n      _id: {\n        $ifNull: [\n          '$QualysScan.scan_data.os',\n          '$CrowdstrikeScan.scan_data.os_version',\n          '$TenableScan.scan_data.operating_systems'\n        ]\n      },\n      Count: { $sum: 1 },\n      Hosts: {\n        $push: '$hostname' \n      }\n    }\n  },\n  {\n    $project: {\n      'Operating System': '$_id',\n      Count: 1,\n      Hosts: 1,\n      _id: 0\n    }\n  },\n  {\n    $sort: {\n      Count: -1 // Sort by Count in descending order\n    }\n  }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "All data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "All data",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "target": "db.normalized.aggregate([{\"$match\": {}}])",
       "type": "table"
      }
     ]
    },
    {
     "title": "All data",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 10, "x": 13, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "target": "db.normalized.aggregate([{\"$match\": {}}])",
       "type": "table"
      }
     ]
    }
   ]
  }
 ]
}